docker-compose build failed of .devcontainer, folder tests is missing
output of docker-compose build before this change:

+ /home/wekan/.meteor/meteor build --directory /home/wekan/app_build
Errors prevented bundling:
While building the application:
error: Could not resolve meteor.mainModule "tests/main.js" in package.json (os)
error: Could not resolve meteor.mainModule "tests/main.js" in package.json
(web.browser)
error: Could not resolve meteor.mainModule "tests/main.js" in package.json
(web.browser.legacy)

The command '/bin/sh -c set -o xtrace &&     cd /home/wekan/app &&     /home/wekan/.meteor/meteor add standard-minifier-js &&     /home/wekan/.meteor/meteor npm install &&     /home/wekan/.meteor/meteor build --directory /home/wekan/app_build' returned a non-zero code: 1